parameters:
  app.mailer_from_email: '%env(MAILER_FROM_EMAIL)%'
  app.mailer_from_name: '%env(MAILER_FROM_NAME)%'

services:
  _defaults:
    autowire: true
    autoconfigure: true


    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
   # Configuration du service de modération (FRANÇAIS)
    App\Service\HuggingFaceModerationService:
        arguments:
            $huggingfaceApiKey: '%env(HUGGINGFACE_API_KEY)%'
            $moderationConfig:
                model: 'facebook/xlm-roberta-base' # Modèle multilingue
                toxicity_threshold: 70  # Bloquer si score >= 70
                warning_threshold: 50   # Avertir si score >= 50


  # Définir explicitement le service PaymeeService
  App\Service\PaymeeService:
    arguments:
      $apiKey: '%env(PAYMEE_API_KEY)%'
      $apiToken: '%env(PAYMEE_API_TOKEN)%'
      $sandbox: '%env(bool:PAYMEE_SANDBOX)%'
