parameters:
  app.mailer_from_email: '%env(MAILER_FROM_EMAIL)%'
  app.mailer_from_name: '%env(MAILER_FROM_NAME)%'

services:
  _defaults:
    autowire: true
    autoconfigure: true

  # Rendre les classes du dossier src/ disponibles comme services automatiquement
  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  # Définir explicitement le service PaymeeService
  App\Service\PaymeeService:
    arguments:
      $apiKey: '%env(PAYMEE_API_KEY)%'
      $apiToken: '%env(PAYMEE_API_TOKEN)%'
      $sandbox: '%env(bool:PAYMEE_SANDBOX)%'
